import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import About from "../src/components/about/About";
import Faq from "../src/components/faq/Faq";
import Main from "../src/components/main/Main";
import Registration from "../src/components/registration/Registration";
import Schedule from "../src/components/schedule/Schedule";
import Sponsors from "../src/components/sponsors/Sponsors";
import TrackChallenge from "../src/components/tracks_and_challenges/BaseChallengeTrack";

import links from "../src/components/navbar/nav.json";
import Navbar from "../src/components/navbar/Navbar";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Template Event Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar anchors={links.components} />
      <div id="home">
        <Main toJump="#registration" />
      </div>
      <div id="about">
        <About />
      </div>
      <div id="tracks_and_challenges">
        <TrackChallenge />
      </div>
      <div id="registration">
        <Registration />
      </div>
      <div id="schedule">
        <Schedule />
      </div>
      <div id="faq">
        <Faq />
      </div>
      <div id="sponsors">
        <Sponsors />
      </div>
    </div>
  );
};

export default Home;
