import type { NextPage } from "next";
import Head from "next/head";
import About from "../components/about/About";
import Faq from "../components/faq/Faq";
import Main from "../components/main/Main";
import Registration from "../components/registration/Registration";
import Schedule from "../components/schedule/Schedule";
import Sponsors from "../components/sponsors/Sponsors";
import TrackChallenge from "../components/tracks_and_challenges/BaseChallengeTrack";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main toJump="#registration" />
      <About />
      <TrackChallenge />
      <div id="registration">
        <Registration />
      </div>
      <Schedule />
      <Faq />
      <Sponsors />
    </div>
  );
};

export default Home;
